CHESS-17: start interacting with the backend
Duzhinsky/chess pull request #23
Opened 2023-06-04 12:58 UTC by Darnelo-Inc

2023-06-04 17:34 UTC, Darnelo-Inc commented
this comment for me in the future when you finish this pull request

2023-06-11 11:51 UTC, Duzhinsky requested changes

2023-06-11 11:51 UTC, Duzhinsky commented on .vscode/launch.json
remove this

2023-06-11 11:58 UTC, Duzhinsky approved these changes

2023-06-11 11:58 UTC, Darnelo-Inc commented on .vscode/launch.json
ok

2023-06-11 11:58 UTC, merged